MvcCubosExamenSAM/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MvcCubosExamenSAM.Filters;
using MvcCubosExamenSAM.Services;
using System.Security.Claims;

namespace MvcCubosExamenSAM.Controllers
{
    public class ManagedController : Controller
    {
        private ServiceUsuarios service;
        public ManagedController(ServiceUsuarios service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            string token = await this.service.LoginAsync(username, password);
            if (token != null)
            {
                HttpContext.Session.SetString("token", token);
                ClaimsIdentity identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
                identity.AddClaim(new Claim(ClaimTypes.Name, username));
                ClaimsPrincipal userPrincipal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, userPrincipal, new AuthenticationProperties
                {
                    ExpiresUtc = DateTime.UtcNow.AddMinutes(5)
                });
                string controller = TempData["controller"].ToString();
                string action = TempData["action"].ToString();
                if (TempData["id"] != null)
                {
                    string id = TempData["id"].ToString();
                    return RedirectToAction(action, controller, new { id = id });
                }
                return RedirectToAction(action, controller);

            }
            else
            {
                ViewData["Error"] = "El correo electronico no existe.";
                return View();
            }
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync
                (CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("token");
            return RedirectToAction("Cubos", "Cubos");
        }
    }
}

MvcCubosExamenSAM/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCubosExamenSAM.Filters;
using MvcCubosExamenSAM.Models;
using MvcCubosExamenSAM.Services;

namespace MvcCubosExamenSAM.Controllers
{
    public class UsuariosController : Controller
    {
        ServiceUsuarios service;
        ServiceBlobs serviceBlobs;
        public UsuariosController(ServiceUsuarios service, ServiceBlobs serviceBlobs)
        {
            this.service = service;
            this.serviceBlobs = serviceBlobs;
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> Perfil()
        {
            Usuario usuario = await this.service.PerfilAsync(HttpContext.Session.GetString("token"));
            string uri = await this.serviceBlobs.GetBlobUriPrivateAsync("imagenesusuarios", usuario.Imagen);
            usuario.Imagen = uri;
            return View(usuario);
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> Pedidos()
        {
            return View(await this.service.PedidosUsuarioAsync(HttpContext.Session.GetString("token")));
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> Comprar(int id)
        {
            await this.service.CrearPedidoAsync(new CompraCuboModel { IdCubo = id, FechaPedido = DateTime.Now }, HttpContext.Session.GetString("token"));
            return RedirectToAction("Pedidos");
        }

        public IActionResult CrearUsuario()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CrearUsuario(UsuarioModel model, IFormFile imagenusuario)
        {
            using (Stream stream = imagenusuario.OpenReadStream())
            {
                await this.serviceBlobs.UploadBlobAsync("imagenesusuarios", imagenusuario.FileName, stream);
            }
            model.Imagen = imagenusuario.FileName;
            await this.service.CrearUsuarioAsync(model);
            return RedirectToAction("Cubos", "Cubos");
        }
    }
}

MvcCubosExamenSAM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCubosExamenSAM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCubosExamenSAM.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCubosExamenSAM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cubos" asp-action="Cubos">Cubos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="CrearUsuario">Crear Usuario</a>
                        </li>
                        <partial name="_MenuUsuario" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCubosExamenSAM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcCubosExamenSAM/Views/Shared/_MenuUsuario.cshtml
@if (Context.User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link text-danger"
       asp-controller="Usuarios"
       asp-action="Perfil">
            Perfil
        </a>
    </li>
        <li class="nav-item">
        <a class="nav-link text-danger"
       asp-controller="Usuarios"
       asp-action="Pedidos">
            Pedidos
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark"
       asp-controller="Managed"
       asp-action="Logout">
            Log Out
            <span style="color:blue">@Context.User.Identity.Name</span>
        </a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-danger"
       asp-controller="Usuarios"
       asp-action="Perfil">
            Log In
        </a>
    </li>
}